### ISSUE TITLE
Review Chart Library

### ISSUE THREAD

**Issue by leo-dh** [loocurse/qc-trading-sim#3]
Might want to look at alternatives other than ApexCharts.js.
Hard to work with their library given their state of documentation.

Alternatives:

- [Visx](https://airbnb.io/visx)
- [React-Vis](http://uber.github.io/react-vis/)
- [Nivo](https://nivo.rocks/)
- [Recharts](https://recharts.org/en-US/)

**Comment by ember-island-engineer** [comment]
Do we want to try [react-financial-charts](https://reactivemarkets.github.io/)? Looks quite comprehensive and more custom towards our purposes.  This is their repo: https://github.com/reactivemarkets/react-financial-charts

**Comment by leo-dh** [comment]
> Do we want to try [react-financial-charts](https://reactivemarkets.github.io/)? Looks quite comprehensive and more custom towards our purposes. This is their repo: https://github.com/reactivemarkets/react-financial-charts

The features look pretty good, I think I'll test it for now. I can't seem to find their full documentation though. Currently, the [storybook](https://reactivemarkets.github.io/react-financial-charts/?path=/story/intro--page) that they have provided don't show the full code snippet for each component so I have to go to their repo to fish out the source.

**Comment by ember-island-engineer** [comment]
Based on Piau's latest inputs, we might not need all the technical indicators. Instead, we need to think of a way to visualize the algorithm's output. This is dependent on how the algorithm will operate. Can KIV the library and discuss with the rest of the team.

**Comment by leo-dh** [comment]
I tried using [react-financial-charts](https://reactivemarkets.github.io/). The features seem pretty decent although it kinda suffers from the lack of docs. Just FYI for now.

![2021-05-28-16:47:37-screenshot](https://user-images.githubusercontent.com/54761622/119957237-7c0b0100-bfd4-11eb-8166-07634d1a49a4.png)

Check the following commit if you want to try it. 
3c5aeb2b0fccd9ed7e27fd5fa16979decdd4ede8
